# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kyc_pb2 as kyc__pb2


class KYCServiceStub(object):
    """The KYC service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckKYC = channel.unary_unary(
                '/kyc.KYCService/CheckKYC',
                request_serializer=kyc__pb2.KYCRequest.SerializeToString,
                response_deserializer=kyc__pb2.KYCResponse.FromString,
                )


class KYCServiceServicer(object):
    """The KYC service definition.
    """

    def CheckKYC(self, request, context):
        """Sends a KYC request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KYCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckKYC': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckKYC,
                    request_deserializer=kyc__pb2.KYCRequest.FromString,
                    response_serializer=kyc__pb2.KYCResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kyc.KYCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KYCService(object):
    """The KYC service definition.
    """

    @staticmethod
    def CheckKYC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kyc.KYCService/CheckKYC',
            kyc__pb2.KYCRequest.SerializeToString,
            kyc__pb2.KYCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
