<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyc.proto

namespace Kyc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message containing KYC results.
 *
 * Generated from protobuf message <code>kyc.KYCResponse</code>
 */
class KYCResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool verified = 1;</code>
     */
    protected $verified = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $verified
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kyc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool verified = 1;</code>
     * @return bool
     */
    public function getVerified()
    {
        return $this->verified;
    }

    /**
     * Generated from protobuf field <code>bool verified = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->verified = $var;

        return $this;
    }

}

