<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kyc.proto

namespace Kyc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message containing the document.
 *
 * Generated from protobuf message <code>kyc.KYCRequest</code>
 */
class KYCRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string document_content = 1;</code>
     */
    protected $document_content = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $document_content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Kyc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string document_content = 1;</code>
     * @return string
     */
    public function getDocumentContent()
    {
        return $this->document_content;
    }

    /**
     * Generated from protobuf field <code>string document_content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->document_content = $var;

        return $this;
    }

}

